WITH raw_collaboration_request AS (
    SELECT * FROM AV_EDM.AV_SOURCE.src_ab_sf_collaborationrequest
)
SELECT id::VARCHAR AS id
    ,name::VARCHAR AS name
    ,ownerid::VARCHAR AS owner_id
    ,collabrawidnumber__c::FLOAT AS collabrawidnumber
    ,team__c::VARCHAR AS team
    ,amount__c::FLOAT AS amount
    ,region__c::VARCHAR AS region
    ,hq_city__c::VARCHAR AS hq_city
    ,hq_country__c::VARCHAR AS hq_country
    ,partner__c::VARCHAR AS partner
    ,arr_100k__C::BOOLEAN AS arr_100k
    ,audience__c::VARCHAR AS audience
    ,location__c::VARCHAR AS location
    ,sub_team__c::VARCHAR AS sub_team
    ,to_stage__c::VARCHAR AS to_stage
    ,from_stage__c::VARCHAR AS from_stage
    ,qs_status__c::VARCHAR AS qs_status
    ,recordtypeid::VARCHAR AS record_type_id
    ,requestor__c::VARCHAR AS requestor
    ,oa_task_id__c::VARCHAR AS oa_task_id
    ,client_type__c::VARCHAR AS client_type
    ,qs_due_date__c::DATE AS qs_due_date
    ,status_note__c::VARCHAR AS status_note
    ,currencyisocode::VARCHAR AS currency_iso_code
    ,partner_type__c::VARCHAR AS partner_type
    ,scoping_team__c::VARCHAR AS scoping_team
    ,customer_type__c::VARCHAR AS customer_type
    ,modernization__c::VARCHAR AS modernization
    ,qs_department__c::VARCHAR AS qs_department
    ,request_count__c::FLOAT AS request_count
    ,estimated_days__c::FLOAT AS estimated_days
    ,estimated_fees__c::FLOAT AS estimated_fees
    ,estimated_hours__c::FLOAT AS estimated_hours
    ,qs_account_name__c::VARCHAR AS qs_account_name
    ,qs_request_type__c::VARCHAR AS qs_request_type
    ,customer_profile__c::VARCHAR AS customer_profile
    ,external_counsel__c::BOOLEAN AS external_counsel
    ,opportunity_close_date__c::DATE AS opportunity_close_date
    ,account_deployment_type__c::VARCHAR AS account_deployment_type
    ,qs_am_i_assigned_owner__c::BOOLEAN AS qs_am_i_assigned_owner
    ,application_of_interest__c::VARCHAR AS application_of_interest
    ,qs_target_completion_date__c::DATE AS qs_target_completion_date
    ,date_delivered_to_customer__c::DATE AS date_delivered_to_customer
    ,opportunity_stage_on_create__c::VARCHAR AS opportunity_stage_on_create
    ,opportunity_stage_on_complete__c::VARCHAR AS opportunity_stage_on_complete
    ,opportunity_application_of_interest__c::VARCHAR AS opportunity_application_of_interest
    ,opportunity_advanced_within_2_weeks__c::BOOLEAN AS opportunity_advanced_within_2_weeks
    ,results_adjusted_per_product_review__c::BOOLEAN AS results_adjusted_per_product_review
    ,unqualified_to_qualified_progression__c::BOOLEAN AS unqualified_to_qualified_progression
    ,isdeleted::BOOLEAN AS is_deleted
    ,createdbyid::VARCHAR AS created_by_id
    ,createddate::TIMESTAMP_NTZ AS created_date
    ,lastmodifiedbyid::VARCHAR AS last_modified_by_id
    ,lastmodifieddate::TIMESTAMP_NTZ AS last_modified_date
    ,systemmodstamp::TIMESTAMP_NTZ AS system_mod_stamp
    ,_airbyte_extracted_at::TIMESTAMP_TZ AS raw_updated
FROM raw_collaboration_request