WITH account_raw AS (
    SELECT * FROM AV_EDM.AV_SOURCE.src_ab_sf_account
)
SELECT id AS id
    ,name AS name
    ,type AS type
    ,primary_investor_type__c AS primary_investor_type
    ,tam__c AS tam
    ,segment__c AS segment
    ,segmentation__c AS segmentation
    ,client_vertical__c AS client_vertical
    ,deployment_type__c AS deployment_type
    ,tier__c AS tier
    ,aum_m__c AS aum_m
    ,client_prioritization__c AS client_priortization
    ,finance_arr__c::FLOAT AS finance_arr
    ,health_score__c AS health_score
    ,nps_score__c AS nps_score
    ,arr_by_customer_asset__c::FLOAT AS arr_by_customer_asset
    ,csm_comments__c AS csm_comments
    ,netsuite_id__c::INT AS netsuite_id
    ,openair_id__c::INT AS openair_id
    ,billingaddress AS billing_address
    ,shippingaddress AS shipping_address
    ,hq_country__c as hq_country
    ,hq_global_region__c as hq_global_region
    ,initial_go_live_date__c::TIMESTAMP_TZ as initial_go_live_date
    ,current_Year_risk_forecast__c as current_year_risk_forecast
    ,next_year_risk_forecast__c as next_year_risk_forecast
    ,risk_forecast_reason__c as risk_forecast_reason
    ,isdeleted::BOOLEAN AS isdeleted
    ,parentid AS parentid
    ,billingcity AS billingcity
    ,billingstate AS billingstate
    ,billingcountry as billingcountry
    ,shippingcity AS shippingcity
    ,shippingstate AS shippingstate
    ,shippingcountry as shippingcountry
    ,phone AS phone
    ,website AS website
    ,ownership AS ownership
    ,numberofemployees::INT AS numberofemployees
    ,tickersymbol AS tickersymbol
    ,industry AS industry
    ,annualrevenue::FLOAT AS annualrevenue
    ,sic as sic
    ,sicdesc as sicdescription
    ,description AS description
    ,ownerid as ownerid
    ,recordtypeid AS recordtypeid
    ,qs_csm__c::VARCHAR AS csm_id
    ,csm_name__c::VARCHAR AS csm_name__c
    ,SALES_ACCOUNT_MANAGER_LOOK_UP__C::VARCHAR AS sales_account_manager_id
    ,sales_account_manager_name__c::VARCHAR AS sales_account_manager_name
    ,SALES_CREDIT_OWNER_LOOK_UP__C::VARCHAR AS sales_credit_owner_id
    ,SALES_EQUITY_OWNER_LOOK_UP__C::VARCHAR AS sales_equity_owner_id
    ,systemmodstamp::TIMESTAMP_TZ AS sys_updated
    ,createddate::TIMESTAMP_TZ AS sys_created
    ,createdbyid AS createdbyid
    ,lastmodifiedbyid AS lastmodifiedbyid
    ,lastmodifieddate::TIMESTAMP_TZ AS lastmodifieddate
    ,_airbyte_extracted_at::TIMESTAMP_TZ AS raw_updated 
FROM account_raw